# 这是我的yml文件

name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
#    - name: First interaction
#      uses: actions/first-interaction@v1.1.1
    
    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
    
    - name: build project
      run: |
           pwd
           ls -R
           gcc hello.c -o ./out/hello
           ls -R
           ./out/hello
    - uses: actions/download-artifact@v3
#      with:
#        name: helloworld   
    - name: Display structure of downloaded files
      run: ls -R   
